# Generated by Django 5.1.6 on 2025-02-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackinghistory",
            name="amt",
            field=models.IntegerField(),
        ),
    ]
