# Generated by Django 5.1.6 on 2025-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_trackinghistory_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackinghistory",
            name="expense_type",
            field=models.CharField(
                choices=[("Credit", "Credit"), ("Debit", "Debit")], max_length=6
            ),
        ),
    ]
